import {
  BarChart3,
  Briefcase,
  CalendarDays,
  DollarSign,
  FileArchive,
  FileText,
  FolderKanban,
  Globe,
  Inbox,
  Laptop,
  LifeBuoy,
  Megaphone,
  Newspaper,
  Receipt,
  Server,
  ShieldCheck,
  Target,
  TrendingUp,
  UserCheck,
  Upload,
  Users,
  Wallet,
} from "lucide-react";
import type { QuickLink } from "@/components/quick-links";
import type { DepartmentCode } from "@/lib/auth";

/** The pages each department opens most, in the order they matter to that team. */
export const DEPARTMENT_QUICK_LINKS: Record<DepartmentCode, QuickLink[]> = {
  it: [
    {
      to: "/it/systems-sites",
      label: "Systems & sites",
      description: "Every website and system IT looks after",
      icon: Server,
    },
    {
      to: "/it/tickets",
      label: "Tickets",
      description: "What staff have asked IT to fix",
      icon: LifeBuoy,
    },
    {
      to: "/it/inventory",
      label: "Inventory",
      description: "Laptops, phones and other equipment",
      icon: Laptop,
    },
    {
      to: "/it/hrms-clients",
      label: "HRMS clients",
      description: "Client licences, seats and renewals",
      icon: Users,
    },
    {
      to: "/it/pipeline",
      label: "Client requests",
      description: "Work clients have asked IT to do",
      icon: Inbox,
    },
    {
      to: "/it/documents",
      label: "Documents",
      description: "IT files, guides and handovers",
      icon: FileText,
    },
    {
      to: "/it/reports",
      label: "Reports",
      description: "The monthly report to the CEO",
      icon: BarChart3,
    },
    {
      to: "/it/calendar",
      label: "Calendar",
      description: "Deadlines and what is coming up",
      icon: CalendarDays,
    },
  ],
  marketing: [
    {
      to: "/marketing/leads",
      label: "Leads",
      description: "People who could become clients",
      icon: Target,
    },
    {
      to: "/marketing/campaigns",
      label: "Campaigns",
      description: "What is running and what it costs",
      icon: Megaphone,
    },
    {
      to: "/marketing/blog",
      label: "Blog",
      description: "Write and publish posts",
      icon: Newspaper,
    },
    {
      to: "/marketing/website-analytics",
      label: "Website analytics",
      description: "Visitors and where they come from",
      icon: Globe,
    },
    {
      to: "/marketing/pipeline",
      label: "Client requests",
      description: "Work clients have asked Marketing to do",
      icon: Inbox,
    },
    {
      to: "/marketing/documents",
      label: "Documents",
      description: "Brand files, artwork and decks",
      icon: FileText,
    },
    {
      to: "/marketing/reports",
      label: "Reports",
      description: "The monthly report to the CEO",
      icon: BarChart3,
    },
    {
      to: "/marketing/calendar",
      label: "Calendar",
      description: "Deadlines and what is coming up",
      icon: CalendarDays,
    },
  ],
  hr: [
    {
      to: "/hr/projects",
      label: "HR projects",
      description: "Service-line work running for clients",
      icon: FolderKanban,
    },
    {
      to: "/hr/recruitment",
      label: "Recruitment",
      description: "Drives you are running for clients",
      icon: UserCheck,
    },
    {
      to: "/hr/pipeline",
      label: "Client requests",
      description: "Work clients have asked HR to do",
      icon: Inbox,
    },
    {
      to: "/hr/workspace",
      label: "Clients & contracts",
      description: "Who HR works for and on what terms",
      icon: Briefcase,
    },
    {
      to: "/hr/tasks",
      label: "Tasks",
      description: "Everything the team has to finish",
      icon: FileArchive,
    },
    {
      to: "/hr/documents",
      label: "Documents",
      description: "HR files, policies and templates",
      icon: FileText,
    },
    {
      to: "/hr/reports",
      label: "Reports",
      description: "The monthly report to the CEO",
      icon: BarChart3,
    },
    {
      to: "/hr/calendar",
      label: "Calendar",
      description: "Deadlines and what is coming up",
      icon: CalendarDays,
    },
  ],
  finance: [
    {
      to: "/finance/invoices",
      label: "Invoices & billing",
      description: "Raise invoices and record payments",
      icon: Receipt,
    },
    {
      to: "/finance/debtors",
      label: "Debtors",
      description: "Who owes money and for how long",
      icon: Wallet,
    },
    {
      to: "/finance/expenses",
      label: "Expenses",
      description: "Money going out, and what for",
      icon: DollarSign,
    },
    {
      to: "/finance/revenue",
      label: "Revenue & margin",
      description: "What each service line earns",
      icon: TrendingUp,
    },
    {
      to: "/finance/budgets",
      label: "Budgets",
      description: "What each department planned to spend",
      icon: FolderKanban,
    },
    {
      to: "/finance/payroll-compliance",
      label: "Payroll compliance",
      description: "Statutory returns and due dates",
      icon: ShieldCheck,
    },
    {
      to: "/finance/upload",
      label: "Upload from Excel",
      description: "Bring invoices and payments in from a file",
      icon: Upload,
    },
    {
      to: "/finance/reports",
      label: "Reports",
      description: "The monthly report to the CEO",
      icon: BarChart3,
    },
  ],
  tender: [
    {
      to: "/tender/bid-pipeline",
      label: "Tenders",
      description: "Every bid and the stage it has reached",
      icon: FileArchive,
    },
    {
      to: "/tender/requests",
      label: "Client requests",
      description: "Bids clients have asked us to prepare",
      icon: Inbox,
    },
    {
      to: "/tender/documents",
      label: "Documents",
      description: "Bid documents and what each one needs",
      icon: FileText,
    },
    {
      to: "/tender/workspace",
      label: "Clients & contracts",
      description: "Who we bid for and what was won",
      icon: Briefcase,
    },
    {
      to: "/projects",
      label: "Projects",
      description: "Work that came out of a won bid",
      icon: FolderKanban,
    },
    {
      to: "/tender/reports",
      label: "Reports",
      description: "The monthly report to the CEO",
      icon: BarChart3,
    },
    {
      to: "/tender/calendar",
      label: "Calendar",
      description: "Closing dates and what is coming up",
      icon: CalendarDays,
    },
  ],
  operations: [],
};
