/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTenderRouteImport } from './routes/_authenticated.tender'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated.requests'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated.pipeline'
import { Route as AuthenticatedMarketingOpsRouteImport } from './routes/_authenticated.marketing-ops'
import { Route as AuthenticatedItRouteImport } from './routes/_authenticated.it'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated.hr'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated.finance'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated.departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated.clients'
import { Route as AuthenticatedTenderIndexRouteImport } from './routes/_authenticated.tender.index'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated.requests.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated.reports.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated.projects.index'
import { Route as AuthenticatedPipelineIndexRouteImport } from './routes/_authenticated.pipeline.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated.finance.index'
import { Route as AuthenticatedDepartmentsIndexRouteImport } from './routes/_authenticated.departments.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated.clients.index'
import { Route as AuthenticatedTenderTenderIdRouteImport } from './routes/_authenticated.tender.$tenderId'
import { Route as AuthenticatedRequestsRequestIdRouteImport } from './routes/_authenticated.requests.$requestId'
import { Route as AuthenticatedReportsProjectsRouteImport } from './routes/_authenticated.reports.projects'
import { Route as AuthenticatedReportsDepartmentsRouteImport } from './routes/_authenticated.reports.departments'
import { Route as AuthenticatedProjectsMineRouteImport } from './routes/_authenticated.projects.mine'
import { Route as AuthenticatedProjectsDepartmentRouteImport } from './routes/_authenticated.projects.department'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated.projects.$projectId'
import { Route as AuthenticatedPipelineTendersRouteImport } from './routes/_authenticated.pipeline.tenders'
import { Route as AuthenticatedPipelineProjectsRouteImport } from './routes/_authenticated.pipeline.projects'
import { Route as AuthenticatedPipelineEngagementsRouteImport } from './routes/_authenticated.pipeline.engagements'
import { Route as AuthenticatedFinanceUploadRouteImport } from './routes/_authenticated.finance.upload'
import { Route as AuthenticatedFinanceRevenueRouteImport } from './routes/_authenticated.finance.revenue'
import { Route as AuthenticatedFinanceReportsRouteImport } from './routes/_authenticated.finance.reports'
import { Route as AuthenticatedFinancePayrollComplianceRouteImport } from './routes/_authenticated.finance.payroll-compliance'
import { Route as AuthenticatedFinanceInvoicesRouteImport } from './routes/_authenticated.finance.invoices'
import { Route as AuthenticatedFinanceDebtorsRouteImport } from './routes/_authenticated.finance.debtors'
import { Route as AuthenticatedFinanceBudgetsRouteImport } from './routes/_authenticated.finance.budgets'
import { Route as AuthenticatedDepartmentsDeptIdRouteImport } from './routes/_authenticated.departments.$deptId'
import { Route as AuthenticatedClientsContractsRouteImport } from './routes/_authenticated.clients.contracts'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated.admin.departments'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'
import { Route as AuthenticatedFinanceReportsIndexRouteImport } from './routes/_authenticated.finance.reports.index'
import { Route as AuthenticatedClientsContractsIndexRouteImport } from './routes/_authenticated.clients.contracts.index'
import { Route as AuthenticatedReportsDepartmentsTenderRouteImport } from './routes/_authenticated.reports.departments.tender'
import { Route as AuthenticatedReportsDepartmentsMarketingOpsRouteImport } from './routes/_authenticated.reports.departments.marketing-ops'
import { Route as AuthenticatedReportsDepartmentsItRouteImport } from './routes/_authenticated.reports.departments.it'
import { Route as AuthenticatedReportsDepartmentsHrRouteImport } from './routes/_authenticated.reports.departments.hr'
import { Route as AuthenticatedReportsDepartmentsFinanceRouteImport } from './routes/_authenticated.reports.departments.finance'
import { Route as AuthenticatedFinanceReportsIdRouteImport } from './routes/_authenticated.finance.reports.$id'
import { Route as AuthenticatedClientsContractsIdRouteImport } from './routes/_authenticated.clients.contracts.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTenderRoute = AuthenticatedTenderRouteImport.update({
  id: '/tender',
  path: '/tender',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingOpsRoute =
  AuthenticatedMarketingOpsRouteImport.update({
    id: '/marketing-ops',
    path: '/marketing-ops',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItRoute = AuthenticatedItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenderIndexRoute =
  AuthenticatedTenderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTenderRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedPipelineIndexRoute =
  AuthenticatedPipelineIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPipelineRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedDepartmentsIndexRoute =
  AuthenticatedDepartmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDepartmentsRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedTenderTenderIdRoute =
  AuthenticatedTenderTenderIdRouteImport.update({
    id: '/$tenderId',
    path: '/$tenderId',
    getParentRoute: () => AuthenticatedTenderRoute,
  } as any)
const AuthenticatedRequestsRequestIdRoute =
  AuthenticatedRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AuthenticatedReportsProjectsRoute =
  AuthenticatedReportsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsDepartmentsRoute =
  AuthenticatedReportsDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedProjectsMineRoute =
  AuthenticatedProjectsMineRouteImport.update({
    id: '/mine',
    path: '/mine',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsDepartmentRoute =
  AuthenticatedProjectsDepartmentRouteImport.update({
    id: '/department',
    path: '/department',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedPipelineTendersRoute =
  AuthenticatedPipelineTendersRouteImport.update({
    id: '/tenders',
    path: '/tenders',
    getParentRoute: () => AuthenticatedPipelineRoute,
  } as any)
const AuthenticatedPipelineProjectsRoute =
  AuthenticatedPipelineProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedPipelineRoute,
  } as any)
const AuthenticatedPipelineEngagementsRoute =
  AuthenticatedPipelineEngagementsRouteImport.update({
    id: '/engagements',
    path: '/engagements',
    getParentRoute: () => AuthenticatedPipelineRoute,
  } as any)
const AuthenticatedFinanceUploadRoute =
  AuthenticatedFinanceUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceRevenueRoute =
  AuthenticatedFinanceRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceReportsRoute =
  AuthenticatedFinanceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinancePayrollComplianceRoute =
  AuthenticatedFinancePayrollComplianceRouteImport.update({
    id: '/payroll-compliance',
    path: '/payroll-compliance',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceInvoicesRoute =
  AuthenticatedFinanceInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceDebtorsRoute =
  AuthenticatedFinanceDebtorsRouteImport.update({
    id: '/debtors',
    path: '/debtors',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceBudgetsRoute =
  AuthenticatedFinanceBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedDepartmentsDeptIdRoute =
  AuthenticatedDepartmentsDeptIdRouteImport.update({
    id: '/$deptId',
    path: '/$deptId',
    getParentRoute: () => AuthenticatedDepartmentsRoute,
  } as any)
const AuthenticatedClientsContractsRoute =
  AuthenticatedClientsContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceReportsIndexRoute =
  AuthenticatedFinanceReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceReportsRoute,
  } as any)
const AuthenticatedClientsContractsIndexRoute =
  AuthenticatedClientsContractsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsContractsRoute,
  } as any)
const AuthenticatedReportsDepartmentsTenderRoute =
  AuthenticatedReportsDepartmentsTenderRouteImport.update({
    id: '/tender',
    path: '/tender',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedReportsDepartmentsMarketingOpsRoute =
  AuthenticatedReportsDepartmentsMarketingOpsRouteImport.update({
    id: '/marketing-ops',
    path: '/marketing-ops',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedReportsDepartmentsItRoute =
  AuthenticatedReportsDepartmentsItRouteImport.update({
    id: '/it',
    path: '/it',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedReportsDepartmentsHrRoute =
  AuthenticatedReportsDepartmentsHrRouteImport.update({
    id: '/hr',
    path: '/hr',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedReportsDepartmentsFinanceRoute =
  AuthenticatedReportsDepartmentsFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedFinanceReportsIdRoute =
  AuthenticatedFinanceReportsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFinanceReportsRoute,
  } as any)
const AuthenticatedClientsContractsIdRoute =
  AuthenticatedClientsContractsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientsContractsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/hr': typeof AuthenticatedHrRoute
  '/it': typeof AuthenticatedItRoute
  '/marketing-ops': typeof AuthenticatedMarketingOpsRoute
  '/pipeline': typeof AuthenticatedPipelineRouteWithChildren
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/tender': typeof AuthenticatedTenderRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/contracts': typeof AuthenticatedClientsContractsRouteWithChildren
  '/departments/$deptId': typeof AuthenticatedDepartmentsDeptIdRoute
  '/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/finance/debtors': typeof AuthenticatedFinanceDebtorsRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/payroll-compliance': typeof AuthenticatedFinancePayrollComplianceRoute
  '/finance/reports': typeof AuthenticatedFinanceReportsRouteWithChildren
  '/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/finance/upload': typeof AuthenticatedFinanceUploadRoute
  '/pipeline/engagements': typeof AuthenticatedPipelineEngagementsRoute
  '/pipeline/projects': typeof AuthenticatedPipelineProjectsRoute
  '/pipeline/tenders': typeof AuthenticatedPipelineTendersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/department': typeof AuthenticatedProjectsDepartmentRoute
  '/projects/mine': typeof AuthenticatedProjectsMineRoute
  '/reports/departments': typeof AuthenticatedReportsDepartmentsRouteWithChildren
  '/reports/projects': typeof AuthenticatedReportsProjectsRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/tender/$tenderId': typeof AuthenticatedTenderTenderIdRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/departments/': typeof AuthenticatedDepartmentsIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/pipeline/': typeof AuthenticatedPipelineIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/tender/': typeof AuthenticatedTenderIndexRoute
  '/clients/contracts/$id': typeof AuthenticatedClientsContractsIdRoute
  '/finance/reports/$id': typeof AuthenticatedFinanceReportsIdRoute
  '/reports/departments/finance': typeof AuthenticatedReportsDepartmentsFinanceRoute
  '/reports/departments/hr': typeof AuthenticatedReportsDepartmentsHrRoute
  '/reports/departments/it': typeof AuthenticatedReportsDepartmentsItRoute
  '/reports/departments/marketing-ops': typeof AuthenticatedReportsDepartmentsMarketingOpsRoute
  '/reports/departments/tender': typeof AuthenticatedReportsDepartmentsTenderRoute
  '/clients/contracts/': typeof AuthenticatedClientsContractsIndexRoute
  '/finance/reports/': typeof AuthenticatedFinanceReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/hr': typeof AuthenticatedHrRoute
  '/it': typeof AuthenticatedItRoute
  '/marketing-ops': typeof AuthenticatedMarketingOpsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/departments/$deptId': typeof AuthenticatedDepartmentsDeptIdRoute
  '/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/finance/debtors': typeof AuthenticatedFinanceDebtorsRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/payroll-compliance': typeof AuthenticatedFinancePayrollComplianceRoute
  '/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/finance/upload': typeof AuthenticatedFinanceUploadRoute
  '/pipeline/engagements': typeof AuthenticatedPipelineEngagementsRoute
  '/pipeline/projects': typeof AuthenticatedPipelineProjectsRoute
  '/pipeline/tenders': typeof AuthenticatedPipelineTendersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/department': typeof AuthenticatedProjectsDepartmentRoute
  '/projects/mine': typeof AuthenticatedProjectsMineRoute
  '/reports/departments': typeof AuthenticatedReportsDepartmentsRouteWithChildren
  '/reports/projects': typeof AuthenticatedReportsProjectsRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/tender/$tenderId': typeof AuthenticatedTenderTenderIdRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/departments': typeof AuthenticatedDepartmentsIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/pipeline': typeof AuthenticatedPipelineIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/tender': typeof AuthenticatedTenderIndexRoute
  '/clients/contracts/$id': typeof AuthenticatedClientsContractsIdRoute
  '/finance/reports/$id': typeof AuthenticatedFinanceReportsIdRoute
  '/reports/departments/finance': typeof AuthenticatedReportsDepartmentsFinanceRoute
  '/reports/departments/hr': typeof AuthenticatedReportsDepartmentsHrRoute
  '/reports/departments/it': typeof AuthenticatedReportsDepartmentsItRoute
  '/reports/departments/marketing-ops': typeof AuthenticatedReportsDepartmentsMarketingOpsRoute
  '/reports/departments/tender': typeof AuthenticatedReportsDepartmentsTenderRoute
  '/clients/contracts': typeof AuthenticatedClientsContractsIndexRoute
  '/finance/reports': typeof AuthenticatedFinanceReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRouteWithChildren
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/it': typeof AuthenticatedItRoute
  '/_authenticated/marketing-ops': typeof AuthenticatedMarketingOpsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/_authenticated/tender': typeof AuthenticatedTenderRouteWithChildren
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/clients/contracts': typeof AuthenticatedClientsContractsRouteWithChildren
  '/_authenticated/departments/$deptId': typeof AuthenticatedDepartmentsDeptIdRoute
  '/_authenticated/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/_authenticated/finance/debtors': typeof AuthenticatedFinanceDebtorsRoute
  '/_authenticated/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/_authenticated/finance/payroll-compliance': typeof AuthenticatedFinancePayrollComplianceRoute
  '/_authenticated/finance/reports': typeof AuthenticatedFinanceReportsRouteWithChildren
  '/_authenticated/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/_authenticated/finance/upload': typeof AuthenticatedFinanceUploadRoute
  '/_authenticated/pipeline/engagements': typeof AuthenticatedPipelineEngagementsRoute
  '/_authenticated/pipeline/projects': typeof AuthenticatedPipelineProjectsRoute
  '/_authenticated/pipeline/tenders': typeof AuthenticatedPipelineTendersRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/department': typeof AuthenticatedProjectsDepartmentRoute
  '/_authenticated/projects/mine': typeof AuthenticatedProjectsMineRoute
  '/_authenticated/reports/departments': typeof AuthenticatedReportsDepartmentsRouteWithChildren
  '/_authenticated/reports/projects': typeof AuthenticatedReportsProjectsRoute
  '/_authenticated/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/_authenticated/tender/$tenderId': typeof AuthenticatedTenderTenderIdRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/departments/': typeof AuthenticatedDepartmentsIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/pipeline/': typeof AuthenticatedPipelineIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/tender/': typeof AuthenticatedTenderIndexRoute
  '/_authenticated/clients/contracts/$id': typeof AuthenticatedClientsContractsIdRoute
  '/_authenticated/finance/reports/$id': typeof AuthenticatedFinanceReportsIdRoute
  '/_authenticated/reports/departments/finance': typeof AuthenticatedReportsDepartmentsFinanceRoute
  '/_authenticated/reports/departments/hr': typeof AuthenticatedReportsDepartmentsHrRoute
  '/_authenticated/reports/departments/it': typeof AuthenticatedReportsDepartmentsItRoute
  '/_authenticated/reports/departments/marketing-ops': typeof AuthenticatedReportsDepartmentsMarketingOpsRoute
  '/_authenticated/reports/departments/tender': typeof AuthenticatedReportsDepartmentsTenderRoute
  '/_authenticated/clients/contracts/': typeof AuthenticatedClientsContractsIndexRoute
  '/_authenticated/finance/reports/': typeof AuthenticatedFinanceReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/finance'
    | '/hr'
    | '/it'
    | '/marketing-ops'
    | '/pipeline'
    | '/projects'
    | '/reports'
    | '/requests'
    | '/tender'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/users'
    | '/clients/contracts'
    | '/departments/$deptId'
    | '/finance/budgets'
    | '/finance/debtors'
    | '/finance/invoices'
    | '/finance/payroll-compliance'
    | '/finance/reports'
    | '/finance/revenue'
    | '/finance/upload'
    | '/pipeline/engagements'
    | '/pipeline/projects'
    | '/pipeline/tenders'
    | '/projects/$projectId'
    | '/projects/department'
    | '/projects/mine'
    | '/reports/departments'
    | '/reports/projects'
    | '/requests/$requestId'
    | '/tender/$tenderId'
    | '/clients/'
    | '/departments/'
    | '/finance/'
    | '/pipeline/'
    | '/projects/'
    | '/reports/'
    | '/requests/'
    | '/tender/'
    | '/clients/contracts/$id'
    | '/finance/reports/$id'
    | '/reports/departments/finance'
    | '/reports/departments/hr'
    | '/reports/departments/it'
    | '/reports/departments/marketing-ops'
    | '/reports/departments/tender'
    | '/clients/contracts/'
    | '/finance/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/documents'
    | '/hr'
    | '/it'
    | '/marketing-ops'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/users'
    | '/departments/$deptId'
    | '/finance/budgets'
    | '/finance/debtors'
    | '/finance/invoices'
    | '/finance/payroll-compliance'
    | '/finance/revenue'
    | '/finance/upload'
    | '/pipeline/engagements'
    | '/pipeline/projects'
    | '/pipeline/tenders'
    | '/projects/$projectId'
    | '/projects/department'
    | '/projects/mine'
    | '/reports/departments'
    | '/reports/projects'
    | '/requests/$requestId'
    | '/tender/$tenderId'
    | '/clients'
    | '/departments'
    | '/finance'
    | '/pipeline'
    | '/projects'
    | '/reports'
    | '/requests'
    | '/tender'
    | '/clients/contracts/$id'
    | '/finance/reports/$id'
    | '/reports/departments/finance'
    | '/reports/departments/hr'
    | '/reports/departments/it'
    | '/reports/departments/marketing-ops'
    | '/reports/departments/tender'
    | '/clients/contracts'
    | '/finance/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/documents'
    | '/_authenticated/finance'
    | '/_authenticated/hr'
    | '/_authenticated/it'
    | '/_authenticated/marketing-ops'
    | '/_authenticated/pipeline'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/requests'
    | '/_authenticated/tender'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/users'
    | '/_authenticated/clients/contracts'
    | '/_authenticated/departments/$deptId'
    | '/_authenticated/finance/budgets'
    | '/_authenticated/finance/debtors'
    | '/_authenticated/finance/invoices'
    | '/_authenticated/finance/payroll-compliance'
    | '/_authenticated/finance/reports'
    | '/_authenticated/finance/revenue'
    | '/_authenticated/finance/upload'
    | '/_authenticated/pipeline/engagements'
    | '/_authenticated/pipeline/projects'
    | '/_authenticated/pipeline/tenders'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/department'
    | '/_authenticated/projects/mine'
    | '/_authenticated/reports/departments'
    | '/_authenticated/reports/projects'
    | '/_authenticated/requests/$requestId'
    | '/_authenticated/tender/$tenderId'
    | '/_authenticated/clients/'
    | '/_authenticated/departments/'
    | '/_authenticated/finance/'
    | '/_authenticated/pipeline/'
    | '/_authenticated/projects/'
    | '/_authenticated/reports/'
    | '/_authenticated/requests/'
    | '/_authenticated/tender/'
    | '/_authenticated/clients/contracts/$id'
    | '/_authenticated/finance/reports/$id'
    | '/_authenticated/reports/departments/finance'
    | '/_authenticated/reports/departments/hr'
    | '/_authenticated/reports/departments/it'
    | '/_authenticated/reports/departments/marketing-ops'
    | '/_authenticated/reports/departments/tender'
    | '/_authenticated/clients/contracts/'
    | '/_authenticated/finance/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tender': {
      id: '/_authenticated/tender'
      path: '/tender'
      fullPath: '/tender'
      preLoaderRoute: typeof AuthenticatedTenderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing-ops': {
      id: '/_authenticated/marketing-ops'
      path: '/marketing-ops'
      fullPath: '/marketing-ops'
      preLoaderRoute: typeof AuthenticatedMarketingOpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/it': {
      id: '/_authenticated/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof AuthenticatedItRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tender/': {
      id: '/_authenticated/tender/'
      path: '/'
      fullPath: '/tender/'
      preLoaderRoute: typeof AuthenticatedTenderIndexRouteImport
      parentRoute: typeof AuthenticatedTenderRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/pipeline/': {
      id: '/_authenticated/pipeline/'
      path: '/'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof AuthenticatedPipelineIndexRouteImport
      parentRoute: typeof AuthenticatedPipelineRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/departments/': {
      id: '/_authenticated/departments/'
      path: '/'
      fullPath: '/departments/'
      preLoaderRoute: typeof AuthenticatedDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedDepartmentsRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/tender/$tenderId': {
      id: '/_authenticated/tender/$tenderId'
      path: '/$tenderId'
      fullPath: '/tender/$tenderId'
      preLoaderRoute: typeof AuthenticatedTenderTenderIdRouteImport
      parentRoute: typeof AuthenticatedTenderRoute
    }
    '/_authenticated/requests/$requestId': {
      id: '/_authenticated/requests/$requestId'
      path: '/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_authenticated/reports/projects': {
      id: '/_authenticated/reports/projects'
      path: '/projects'
      fullPath: '/reports/projects'
      preLoaderRoute: typeof AuthenticatedReportsProjectsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/departments': {
      id: '/_authenticated/reports/departments'
      path: '/departments'
      fullPath: '/reports/departments'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/projects/mine': {
      id: '/_authenticated/projects/mine'
      path: '/mine'
      fullPath: '/projects/mine'
      preLoaderRoute: typeof AuthenticatedProjectsMineRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/department': {
      id: '/_authenticated/projects/department'
      path: '/department'
      fullPath: '/projects/department'
      preLoaderRoute: typeof AuthenticatedProjectsDepartmentRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/pipeline/tenders': {
      id: '/_authenticated/pipeline/tenders'
      path: '/tenders'
      fullPath: '/pipeline/tenders'
      preLoaderRoute: typeof AuthenticatedPipelineTendersRouteImport
      parentRoute: typeof AuthenticatedPipelineRoute
    }
    '/_authenticated/pipeline/projects': {
      id: '/_authenticated/pipeline/projects'
      path: '/projects'
      fullPath: '/pipeline/projects'
      preLoaderRoute: typeof AuthenticatedPipelineProjectsRouteImport
      parentRoute: typeof AuthenticatedPipelineRoute
    }
    '/_authenticated/pipeline/engagements': {
      id: '/_authenticated/pipeline/engagements'
      path: '/engagements'
      fullPath: '/pipeline/engagements'
      preLoaderRoute: typeof AuthenticatedPipelineEngagementsRouteImport
      parentRoute: typeof AuthenticatedPipelineRoute
    }
    '/_authenticated/finance/upload': {
      id: '/_authenticated/finance/upload'
      path: '/upload'
      fullPath: '/finance/upload'
      preLoaderRoute: typeof AuthenticatedFinanceUploadRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/revenue': {
      id: '/_authenticated/finance/revenue'
      path: '/revenue'
      fullPath: '/finance/revenue'
      preLoaderRoute: typeof AuthenticatedFinanceRevenueRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/reports': {
      id: '/_authenticated/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof AuthenticatedFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/payroll-compliance': {
      id: '/_authenticated/finance/payroll-compliance'
      path: '/payroll-compliance'
      fullPath: '/finance/payroll-compliance'
      preLoaderRoute: typeof AuthenticatedFinancePayrollComplianceRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/invoices': {
      id: '/_authenticated/finance/invoices'
      path: '/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AuthenticatedFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/debtors': {
      id: '/_authenticated/finance/debtors'
      path: '/debtors'
      fullPath: '/finance/debtors'
      preLoaderRoute: typeof AuthenticatedFinanceDebtorsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/budgets': {
      id: '/_authenticated/finance/budgets'
      path: '/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof AuthenticatedFinanceBudgetsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/departments/$deptId': {
      id: '/_authenticated/departments/$deptId'
      path: '/$deptId'
      fullPath: '/departments/$deptId'
      preLoaderRoute: typeof AuthenticatedDepartmentsDeptIdRouteImport
      parentRoute: typeof AuthenticatedDepartmentsRoute
    }
    '/_authenticated/clients/contracts': {
      id: '/_authenticated/clients/contracts'
      path: '/contracts'
      fullPath: '/clients/contracts'
      preLoaderRoute: typeof AuthenticatedClientsContractsRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/reports/': {
      id: '/_authenticated/finance/reports/'
      path: '/'
      fullPath: '/finance/reports/'
      preLoaderRoute: typeof AuthenticatedFinanceReportsIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceReportsRoute
    }
    '/_authenticated/clients/contracts/': {
      id: '/_authenticated/clients/contracts/'
      path: '/'
      fullPath: '/clients/contracts/'
      preLoaderRoute: typeof AuthenticatedClientsContractsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsContractsRoute
    }
    '/_authenticated/reports/departments/tender': {
      id: '/_authenticated/reports/departments/tender'
      path: '/tender'
      fullPath: '/reports/departments/tender'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsTenderRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/reports/departments/marketing-ops': {
      id: '/_authenticated/reports/departments/marketing-ops'
      path: '/marketing-ops'
      fullPath: '/reports/departments/marketing-ops'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsMarketingOpsRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/reports/departments/it': {
      id: '/_authenticated/reports/departments/it'
      path: '/it'
      fullPath: '/reports/departments/it'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsItRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/reports/departments/hr': {
      id: '/_authenticated/reports/departments/hr'
      path: '/hr'
      fullPath: '/reports/departments/hr'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsHrRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/reports/departments/finance': {
      id: '/_authenticated/reports/departments/finance'
      path: '/finance'
      fullPath: '/reports/departments/finance'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsFinanceRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/finance/reports/$id': {
      id: '/_authenticated/finance/reports/$id'
      path: '/$id'
      fullPath: '/finance/reports/$id'
      preLoaderRoute: typeof AuthenticatedFinanceReportsIdRouteImport
      parentRoute: typeof AuthenticatedFinanceReportsRoute
    }
    '/_authenticated/clients/contracts/$id': {
      id: '/_authenticated/clients/contracts/$id'
      path: '/$id'
      fullPath: '/clients/contracts/$id'
      preLoaderRoute: typeof AuthenticatedClientsContractsIdRouteImport
      parentRoute: typeof AuthenticatedClientsContractsRoute
    }
  }
}

interface AuthenticatedClientsContractsRouteChildren {
  AuthenticatedClientsContractsIdRoute: typeof AuthenticatedClientsContractsIdRoute
  AuthenticatedClientsContractsIndexRoute: typeof AuthenticatedClientsContractsIndexRoute
}

const AuthenticatedClientsContractsRouteChildren: AuthenticatedClientsContractsRouteChildren =
  {
    AuthenticatedClientsContractsIdRoute: AuthenticatedClientsContractsIdRoute,
    AuthenticatedClientsContractsIndexRoute:
      AuthenticatedClientsContractsIndexRoute,
  }

const AuthenticatedClientsContractsRouteWithChildren =
  AuthenticatedClientsContractsRoute._addFileChildren(
    AuthenticatedClientsContractsRouteChildren,
  )

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsContractsRoute: typeof AuthenticatedClientsContractsRouteWithChildren
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsContractsRoute:
    AuthenticatedClientsContractsRouteWithChildren,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedDepartmentsRouteChildren {
  AuthenticatedDepartmentsDeptIdRoute: typeof AuthenticatedDepartmentsDeptIdRoute
  AuthenticatedDepartmentsIndexRoute: typeof AuthenticatedDepartmentsIndexRoute
}

const AuthenticatedDepartmentsRouteChildren: AuthenticatedDepartmentsRouteChildren =
  {
    AuthenticatedDepartmentsDeptIdRoute: AuthenticatedDepartmentsDeptIdRoute,
    AuthenticatedDepartmentsIndexRoute: AuthenticatedDepartmentsIndexRoute,
  }

const AuthenticatedDepartmentsRouteWithChildren =
  AuthenticatedDepartmentsRoute._addFileChildren(
    AuthenticatedDepartmentsRouteChildren,
  )

interface AuthenticatedFinanceReportsRouteChildren {
  AuthenticatedFinanceReportsIdRoute: typeof AuthenticatedFinanceReportsIdRoute
  AuthenticatedFinanceReportsIndexRoute: typeof AuthenticatedFinanceReportsIndexRoute
}

const AuthenticatedFinanceReportsRouteChildren: AuthenticatedFinanceReportsRouteChildren =
  {
    AuthenticatedFinanceReportsIdRoute: AuthenticatedFinanceReportsIdRoute,
    AuthenticatedFinanceReportsIndexRoute:
      AuthenticatedFinanceReportsIndexRoute,
  }

const AuthenticatedFinanceReportsRouteWithChildren =
  AuthenticatedFinanceReportsRoute._addFileChildren(
    AuthenticatedFinanceReportsRouteChildren,
  )

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceBudgetsRoute: typeof AuthenticatedFinanceBudgetsRoute
  AuthenticatedFinanceDebtorsRoute: typeof AuthenticatedFinanceDebtorsRoute
  AuthenticatedFinanceInvoicesRoute: typeof AuthenticatedFinanceInvoicesRoute
  AuthenticatedFinancePayrollComplianceRoute: typeof AuthenticatedFinancePayrollComplianceRoute
  AuthenticatedFinanceReportsRoute: typeof AuthenticatedFinanceReportsRouteWithChildren
  AuthenticatedFinanceRevenueRoute: typeof AuthenticatedFinanceRevenueRoute
  AuthenticatedFinanceUploadRoute: typeof AuthenticatedFinanceUploadRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceBudgetsRoute: AuthenticatedFinanceBudgetsRoute,
  AuthenticatedFinanceDebtorsRoute: AuthenticatedFinanceDebtorsRoute,
  AuthenticatedFinanceInvoicesRoute: AuthenticatedFinanceInvoicesRoute,
  AuthenticatedFinancePayrollComplianceRoute:
    AuthenticatedFinancePayrollComplianceRoute,
  AuthenticatedFinanceReportsRoute:
    AuthenticatedFinanceReportsRouteWithChildren,
  AuthenticatedFinanceRevenueRoute: AuthenticatedFinanceRevenueRoute,
  AuthenticatedFinanceUploadRoute: AuthenticatedFinanceUploadRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedPipelineRouteChildren {
  AuthenticatedPipelineEngagementsRoute: typeof AuthenticatedPipelineEngagementsRoute
  AuthenticatedPipelineProjectsRoute: typeof AuthenticatedPipelineProjectsRoute
  AuthenticatedPipelineTendersRoute: typeof AuthenticatedPipelineTendersRoute
  AuthenticatedPipelineIndexRoute: typeof AuthenticatedPipelineIndexRoute
}

const AuthenticatedPipelineRouteChildren: AuthenticatedPipelineRouteChildren = {
  AuthenticatedPipelineEngagementsRoute: AuthenticatedPipelineEngagementsRoute,
  AuthenticatedPipelineProjectsRoute: AuthenticatedPipelineProjectsRoute,
  AuthenticatedPipelineTendersRoute: AuthenticatedPipelineTendersRoute,
  AuthenticatedPipelineIndexRoute: AuthenticatedPipelineIndexRoute,
}

const AuthenticatedPipelineRouteWithChildren =
  AuthenticatedPipelineRoute._addFileChildren(
    AuthenticatedPipelineRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsDepartmentRoute: typeof AuthenticatedProjectsDepartmentRoute
  AuthenticatedProjectsMineRoute: typeof AuthenticatedProjectsMineRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsDepartmentRoute: AuthenticatedProjectsDepartmentRoute,
  AuthenticatedProjectsMineRoute: AuthenticatedProjectsMineRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedReportsDepartmentsRouteChildren {
  AuthenticatedReportsDepartmentsFinanceRoute: typeof AuthenticatedReportsDepartmentsFinanceRoute
  AuthenticatedReportsDepartmentsHrRoute: typeof AuthenticatedReportsDepartmentsHrRoute
  AuthenticatedReportsDepartmentsItRoute: typeof AuthenticatedReportsDepartmentsItRoute
  AuthenticatedReportsDepartmentsMarketingOpsRoute: typeof AuthenticatedReportsDepartmentsMarketingOpsRoute
  AuthenticatedReportsDepartmentsTenderRoute: typeof AuthenticatedReportsDepartmentsTenderRoute
}

const AuthenticatedReportsDepartmentsRouteChildren: AuthenticatedReportsDepartmentsRouteChildren =
  {
    AuthenticatedReportsDepartmentsFinanceRoute:
      AuthenticatedReportsDepartmentsFinanceRoute,
    AuthenticatedReportsDepartmentsHrRoute:
      AuthenticatedReportsDepartmentsHrRoute,
    AuthenticatedReportsDepartmentsItRoute:
      AuthenticatedReportsDepartmentsItRoute,
    AuthenticatedReportsDepartmentsMarketingOpsRoute:
      AuthenticatedReportsDepartmentsMarketingOpsRoute,
    AuthenticatedReportsDepartmentsTenderRoute:
      AuthenticatedReportsDepartmentsTenderRoute,
  }

const AuthenticatedReportsDepartmentsRouteWithChildren =
  AuthenticatedReportsDepartmentsRoute._addFileChildren(
    AuthenticatedReportsDepartmentsRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsDepartmentsRoute: typeof AuthenticatedReportsDepartmentsRouteWithChildren
  AuthenticatedReportsProjectsRoute: typeof AuthenticatedReportsProjectsRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsDepartmentsRoute:
    AuthenticatedReportsDepartmentsRouteWithChildren,
  AuthenticatedReportsProjectsRoute: AuthenticatedReportsProjectsRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRequestsRouteChildren {
  AuthenticatedRequestsRequestIdRoute: typeof AuthenticatedRequestsRequestIdRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
}

const AuthenticatedRequestsRouteChildren: AuthenticatedRequestsRouteChildren = {
  AuthenticatedRequestsRequestIdRoute: AuthenticatedRequestsRequestIdRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
}

const AuthenticatedRequestsRouteWithChildren =
  AuthenticatedRequestsRoute._addFileChildren(
    AuthenticatedRequestsRouteChildren,
  )

interface AuthenticatedTenderRouteChildren {
  AuthenticatedTenderTenderIdRoute: typeof AuthenticatedTenderTenderIdRoute
  AuthenticatedTenderIndexRoute: typeof AuthenticatedTenderIndexRoute
}

const AuthenticatedTenderRouteChildren: AuthenticatedTenderRouteChildren = {
  AuthenticatedTenderTenderIdRoute: AuthenticatedTenderTenderIdRoute,
  AuthenticatedTenderIndexRoute: AuthenticatedTenderIndexRoute,
}

const AuthenticatedTenderRouteWithChildren =
  AuthenticatedTenderRoute._addFileChildren(AuthenticatedTenderRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRouteWithChildren
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedItRoute: typeof AuthenticatedItRoute
  AuthenticatedMarketingOpsRoute: typeof AuthenticatedMarketingOpsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRouteWithChildren
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRouteWithChildren
  AuthenticatedTenderRoute: typeof AuthenticatedTenderRouteWithChildren
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRouteWithChildren,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedItRoute: AuthenticatedItRoute,
  AuthenticatedMarketingOpsRoute: AuthenticatedMarketingOpsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRouteWithChildren,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRouteWithChildren,
  AuthenticatedTenderRoute: AuthenticatedTenderRouteWithChildren,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
