/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTenderRouteImport } from './routes/_authenticated.tender'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated.requests'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated.pipeline'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated.operations'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated.marketing'
import { Route as AuthenticatedItRouteImport } from './routes/_authenticated.it'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated.hr'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated.guide'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated.finance'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated.departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated.clients'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedTenderIndexRouteImport } from './routes/_authenticated.tender.index'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated.requests.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated.reports.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated.projects.index'
import { Route as AuthenticatedPipelineIndexRouteImport } from './routes/_authenticated.pipeline.index'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated.marketing.index'
import { Route as AuthenticatedItIndexRouteImport } from './routes/_authenticated.it.index'
import { Route as AuthenticatedHrIndexRouteImport } from './routes/_authenticated.hr.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated.finance.index'
import { Route as AuthenticatedDepartmentsIndexRouteImport } from './routes/_authenticated.departments.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated.clients.index'
import { Route as AuthenticatedTenderTenderIdRouteImport } from './routes/_authenticated.tender.$tenderId'
import { Route as AuthenticatedRequestsRequestIdRouteImport } from './routes/_authenticated.requests.$requestId'
import { Route as AuthenticatedReportsProjectsRouteImport } from './routes/_authenticated.reports.projects'
import { Route as AuthenticatedReportsDepartmentsRouteImport } from './routes/_authenticated.reports.departments'
import { Route as AuthenticatedProjectsMineRouteImport } from './routes/_authenticated.projects.mine'
import { Route as AuthenticatedProjectsDepartmentRouteImport } from './routes/_authenticated.projects.department'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated.projects.$projectId'
import { Route as AuthenticatedPipelineTendersRouteImport } from './routes/_authenticated.pipeline.tenders'
import { Route as AuthenticatedPipelineProjectsRouteImport } from './routes/_authenticated.pipeline.projects'
import { Route as AuthenticatedPipelineEngagementsRouteImport } from './routes/_authenticated.pipeline.engagements'
import { Route as AuthenticatedMarketingWebsiteAnalyticsRouteImport } from './routes/_authenticated.marketing.website-analytics'
import { Route as AuthenticatedMarketingLeadsRouteImport } from './routes/_authenticated.marketing.leads'
import { Route as AuthenticatedMarketingCampaignsRouteImport } from './routes/_authenticated.marketing.campaigns'
import { Route as AuthenticatedMarketingBlogRouteImport } from './routes/_authenticated.marketing.blog'
import { Route as AuthenticatedItTicketsRouteImport } from './routes/_authenticated.it.tickets'
import { Route as AuthenticatedItSystemsSitesRouteImport } from './routes/_authenticated.it.systems-sites'
import { Route as AuthenticatedItHrmsClientsRouteImport } from './routes/_authenticated.it.hrms-clients'
import { Route as AuthenticatedHrRecruitmentRouteImport } from './routes/_authenticated.hr.recruitment'
import { Route as AuthenticatedHrProjectsRouteImport } from './routes/_authenticated.hr.projects'
import { Route as AuthenticatedFinanceUploadRouteImport } from './routes/_authenticated.finance.upload'
import { Route as AuthenticatedFinanceRevenueRouteImport } from './routes/_authenticated.finance.revenue'
import { Route as AuthenticatedFinanceReportsRouteImport } from './routes/_authenticated.finance.reports'
import { Route as AuthenticatedFinancePayrollComplianceRouteImport } from './routes/_authenticated.finance.payroll-compliance'
import { Route as AuthenticatedFinanceInvoicesRouteImport } from './routes/_authenticated.finance.invoices'
import { Route as AuthenticatedFinanceDebtorsRouteImport } from './routes/_authenticated.finance.debtors'
import { Route as AuthenticatedFinanceBudgetsRouteImport } from './routes/_authenticated.finance.budgets'
import { Route as AuthenticatedDepartmentsDeptIdRouteImport } from './routes/_authenticated.departments.$deptId'
import { Route as AuthenticatedClientsContractsRouteImport } from './routes/_authenticated.clients.contracts'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated.admin.departments'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'
import { Route as AuthenticatedMarketingBlogIndexRouteImport } from './routes/_authenticated.marketing.blog.index'
import { Route as AuthenticatedFinanceReportsIndexRouteImport } from './routes/_authenticated.finance.reports.index'
import { Route as AuthenticatedClientsContractsIndexRouteImport } from './routes/_authenticated.clients.contracts.index'
import { Route as AuthenticatedReportsDepartmentsTenderRouteImport } from './routes/_authenticated.reports.departments.tender'
import { Route as AuthenticatedReportsDepartmentsMarketingRouteImport } from './routes/_authenticated.reports.departments.marketing'
import { Route as AuthenticatedReportsDepartmentsItRouteImport } from './routes/_authenticated.reports.departments.it'
import { Route as AuthenticatedReportsDepartmentsHrRouteImport } from './routes/_authenticated.reports.departments.hr'
import { Route as AuthenticatedReportsDepartmentsFinanceRouteImport } from './routes/_authenticated.reports.departments.finance'
import { Route as AuthenticatedMarketingBlogPostIdRouteImport } from './routes/_authenticated.marketing.blog.$postId'
import { Route as AuthenticatedFinanceReportsIdRouteImport } from './routes/_authenticated.finance.reports.$id'
import { Route as AuthenticatedEngagementsAnchorTypeAnchorIdRouteImport } from './routes/_authenticated.engagements.$anchorType.$anchorId'
import { Route as AuthenticatedClientsContractsIdRouteImport } from './routes/_authenticated.clients.contracts.$id'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTenderRoute = AuthenticatedTenderRouteImport.update({
  id: '/tender',
  path: '/tender',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItRoute = AuthenticatedItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenderIndexRoute =
  AuthenticatedTenderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTenderRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedPipelineIndexRoute =
  AuthenticatedPipelineIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPipelineRoute,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedItIndexRoute = AuthenticatedItIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedItRoute,
} as any)
const AuthenticatedHrIndexRoute = AuthenticatedHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedDepartmentsIndexRoute =
  AuthenticatedDepartmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDepartmentsRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedTenderTenderIdRoute =
  AuthenticatedTenderTenderIdRouteImport.update({
    id: '/$tenderId',
    path: '/$tenderId',
    getParentRoute: () => AuthenticatedTenderRoute,
  } as any)
const AuthenticatedRequestsRequestIdRoute =
  AuthenticatedRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AuthenticatedReportsProjectsRoute =
  AuthenticatedReportsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsDepartmentsRoute =
  AuthenticatedReportsDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedProjectsMineRoute =
  AuthenticatedProjectsMineRouteImport.update({
    id: '/mine',
    path: '/mine',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsDepartmentRoute =
  AuthenticatedProjectsDepartmentRouteImport.update({
    id: '/department',
    path: '/department',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedPipelineTendersRoute =
  AuthenticatedPipelineTendersRouteImport.update({
    id: '/tenders',
    path: '/tenders',
    getParentRoute: () => AuthenticatedPipelineRoute,
  } as any)
const AuthenticatedPipelineProjectsRoute =
  AuthenticatedPipelineProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedPipelineRoute,
  } as any)
const AuthenticatedPipelineEngagementsRoute =
  AuthenticatedPipelineEngagementsRouteImport.update({
    id: '/engagements',
    path: '/engagements',
    getParentRoute: () => AuthenticatedPipelineRoute,
  } as any)
const AuthenticatedMarketingWebsiteAnalyticsRoute =
  AuthenticatedMarketingWebsiteAnalyticsRouteImport.update({
    id: '/website-analytics',
    path: '/website-analytics',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingLeadsRoute =
  AuthenticatedMarketingLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingCampaignsRoute =
  AuthenticatedMarketingCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingBlogRoute =
  AuthenticatedMarketingBlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedItTicketsRoute = AuthenticatedItTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedItRoute,
} as any)
const AuthenticatedItSystemsSitesRoute =
  AuthenticatedItSystemsSitesRouteImport.update({
    id: '/systems-sites',
    path: '/systems-sites',
    getParentRoute: () => AuthenticatedItRoute,
  } as any)
const AuthenticatedItHrmsClientsRoute =
  AuthenticatedItHrmsClientsRouteImport.update({
    id: '/hrms-clients',
    path: '/hrms-clients',
    getParentRoute: () => AuthenticatedItRoute,
  } as any)
const AuthenticatedHrRecruitmentRoute =
  AuthenticatedHrRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedHrProjectsRoute = AuthenticatedHrProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedFinanceUploadRoute =
  AuthenticatedFinanceUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceRevenueRoute =
  AuthenticatedFinanceRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceReportsRoute =
  AuthenticatedFinanceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinancePayrollComplianceRoute =
  AuthenticatedFinancePayrollComplianceRouteImport.update({
    id: '/payroll-compliance',
    path: '/payroll-compliance',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceInvoicesRoute =
  AuthenticatedFinanceInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceDebtorsRoute =
  AuthenticatedFinanceDebtorsRouteImport.update({
    id: '/debtors',
    path: '/debtors',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceBudgetsRoute =
  AuthenticatedFinanceBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedDepartmentsDeptIdRoute =
  AuthenticatedDepartmentsDeptIdRouteImport.update({
    id: '/$deptId',
    path: '/$deptId',
    getParentRoute: () => AuthenticatedDepartmentsRoute,
  } as any)
const AuthenticatedClientsContractsRoute =
  AuthenticatedClientsContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingBlogIndexRoute =
  AuthenticatedMarketingBlogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketingBlogRoute,
  } as any)
const AuthenticatedFinanceReportsIndexRoute =
  AuthenticatedFinanceReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceReportsRoute,
  } as any)
const AuthenticatedClientsContractsIndexRoute =
  AuthenticatedClientsContractsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsContractsRoute,
  } as any)
const AuthenticatedReportsDepartmentsTenderRoute =
  AuthenticatedReportsDepartmentsTenderRouteImport.update({
    id: '/tender',
    path: '/tender',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedReportsDepartmentsMarketingRoute =
  AuthenticatedReportsDepartmentsMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedReportsDepartmentsItRoute =
  AuthenticatedReportsDepartmentsItRouteImport.update({
    id: '/it',
    path: '/it',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedReportsDepartmentsHrRoute =
  AuthenticatedReportsDepartmentsHrRouteImport.update({
    id: '/hr',
    path: '/hr',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedReportsDepartmentsFinanceRoute =
  AuthenticatedReportsDepartmentsFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedReportsDepartmentsRoute,
  } as any)
const AuthenticatedMarketingBlogPostIdRoute =
  AuthenticatedMarketingBlogPostIdRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => AuthenticatedMarketingBlogRoute,
  } as any)
const AuthenticatedFinanceReportsIdRoute =
  AuthenticatedFinanceReportsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFinanceReportsRoute,
  } as any)
const AuthenticatedEngagementsAnchorTypeAnchorIdRoute =
  AuthenticatedEngagementsAnchorTypeAnchorIdRouteImport.update({
    id: '/engagements/$anchorType/$anchorId',
    path: '/engagements/$anchorType/$anchorId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsContractsIdRoute =
  AuthenticatedClientsContractsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientsContractsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/guide': typeof AuthenticatedGuideRoute
  '/hr': typeof AuthenticatedHrRouteWithChildren
  '/it': typeof AuthenticatedItRouteWithChildren
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/operations': typeof AuthenticatedOperationsRoute
  '/pipeline': typeof AuthenticatedPipelineRouteWithChildren
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/tender': typeof AuthenticatedTenderRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/contracts': typeof AuthenticatedClientsContractsRouteWithChildren
  '/departments/$deptId': typeof AuthenticatedDepartmentsDeptIdRoute
  '/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/finance/debtors': typeof AuthenticatedFinanceDebtorsRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/payroll-compliance': typeof AuthenticatedFinancePayrollComplianceRoute
  '/finance/reports': typeof AuthenticatedFinanceReportsRouteWithChildren
  '/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/finance/upload': typeof AuthenticatedFinanceUploadRoute
  '/hr/projects': typeof AuthenticatedHrProjectsRoute
  '/hr/recruitment': typeof AuthenticatedHrRecruitmentRoute
  '/it/hrms-clients': typeof AuthenticatedItHrmsClientsRoute
  '/it/systems-sites': typeof AuthenticatedItSystemsSitesRoute
  '/it/tickets': typeof AuthenticatedItTicketsRoute
  '/marketing/blog': typeof AuthenticatedMarketingBlogRouteWithChildren
  '/marketing/campaigns': typeof AuthenticatedMarketingCampaignsRoute
  '/marketing/leads': typeof AuthenticatedMarketingLeadsRoute
  '/marketing/website-analytics': typeof AuthenticatedMarketingWebsiteAnalyticsRoute
  '/pipeline/engagements': typeof AuthenticatedPipelineEngagementsRoute
  '/pipeline/projects': typeof AuthenticatedPipelineProjectsRoute
  '/pipeline/tenders': typeof AuthenticatedPipelineTendersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/department': typeof AuthenticatedProjectsDepartmentRoute
  '/projects/mine': typeof AuthenticatedProjectsMineRoute
  '/reports/departments': typeof AuthenticatedReportsDepartmentsRouteWithChildren
  '/reports/projects': typeof AuthenticatedReportsProjectsRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/tender/$tenderId': typeof AuthenticatedTenderTenderIdRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/departments/': typeof AuthenticatedDepartmentsIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/hr/': typeof AuthenticatedHrIndexRoute
  '/it/': typeof AuthenticatedItIndexRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/pipeline/': typeof AuthenticatedPipelineIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/tender/': typeof AuthenticatedTenderIndexRoute
  '/clients/contracts/$id': typeof AuthenticatedClientsContractsIdRoute
  '/engagements/$anchorType/$anchorId': typeof AuthenticatedEngagementsAnchorTypeAnchorIdRoute
  '/finance/reports/$id': typeof AuthenticatedFinanceReportsIdRoute
  '/marketing/blog/$postId': typeof AuthenticatedMarketingBlogPostIdRoute
  '/reports/departments/finance': typeof AuthenticatedReportsDepartmentsFinanceRoute
  '/reports/departments/hr': typeof AuthenticatedReportsDepartmentsHrRoute
  '/reports/departments/it': typeof AuthenticatedReportsDepartmentsItRoute
  '/reports/departments/marketing': typeof AuthenticatedReportsDepartmentsMarketingRoute
  '/reports/departments/tender': typeof AuthenticatedReportsDepartmentsTenderRoute
  '/clients/contracts/': typeof AuthenticatedClientsContractsIndexRoute
  '/finance/reports/': typeof AuthenticatedFinanceReportsIndexRoute
  '/marketing/blog/': typeof AuthenticatedMarketingBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/departments/$deptId': typeof AuthenticatedDepartmentsDeptIdRoute
  '/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/finance/debtors': typeof AuthenticatedFinanceDebtorsRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/payroll-compliance': typeof AuthenticatedFinancePayrollComplianceRoute
  '/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/finance/upload': typeof AuthenticatedFinanceUploadRoute
  '/hr/projects': typeof AuthenticatedHrProjectsRoute
  '/hr/recruitment': typeof AuthenticatedHrRecruitmentRoute
  '/it/hrms-clients': typeof AuthenticatedItHrmsClientsRoute
  '/it/systems-sites': typeof AuthenticatedItSystemsSitesRoute
  '/it/tickets': typeof AuthenticatedItTicketsRoute
  '/marketing/campaigns': typeof AuthenticatedMarketingCampaignsRoute
  '/marketing/leads': typeof AuthenticatedMarketingLeadsRoute
  '/marketing/website-analytics': typeof AuthenticatedMarketingWebsiteAnalyticsRoute
  '/pipeline/engagements': typeof AuthenticatedPipelineEngagementsRoute
  '/pipeline/projects': typeof AuthenticatedPipelineProjectsRoute
  '/pipeline/tenders': typeof AuthenticatedPipelineTendersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/department': typeof AuthenticatedProjectsDepartmentRoute
  '/projects/mine': typeof AuthenticatedProjectsMineRoute
  '/reports/departments': typeof AuthenticatedReportsDepartmentsRouteWithChildren
  '/reports/projects': typeof AuthenticatedReportsProjectsRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/tender/$tenderId': typeof AuthenticatedTenderTenderIdRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/departments': typeof AuthenticatedDepartmentsIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/hr': typeof AuthenticatedHrIndexRoute
  '/it': typeof AuthenticatedItIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/pipeline': typeof AuthenticatedPipelineIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/tender': typeof AuthenticatedTenderIndexRoute
  '/clients/contracts/$id': typeof AuthenticatedClientsContractsIdRoute
  '/engagements/$anchorType/$anchorId': typeof AuthenticatedEngagementsAnchorTypeAnchorIdRoute
  '/finance/reports/$id': typeof AuthenticatedFinanceReportsIdRoute
  '/marketing/blog/$postId': typeof AuthenticatedMarketingBlogPostIdRoute
  '/reports/departments/finance': typeof AuthenticatedReportsDepartmentsFinanceRoute
  '/reports/departments/hr': typeof AuthenticatedReportsDepartmentsHrRoute
  '/reports/departments/it': typeof AuthenticatedReportsDepartmentsItRoute
  '/reports/departments/marketing': typeof AuthenticatedReportsDepartmentsMarketingRoute
  '/reports/departments/tender': typeof AuthenticatedReportsDepartmentsTenderRoute
  '/clients/contracts': typeof AuthenticatedClientsContractsIndexRoute
  '/finance/reports': typeof AuthenticatedFinanceReportsIndexRoute
  '/marketing/blog': typeof AuthenticatedMarketingBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRouteWithChildren
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/guide': typeof AuthenticatedGuideRoute
  '/_authenticated/hr': typeof AuthenticatedHrRouteWithChildren
  '/_authenticated/it': typeof AuthenticatedItRouteWithChildren
  '/_authenticated/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/_authenticated/tender': typeof AuthenticatedTenderRouteWithChildren
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/clients/contracts': typeof AuthenticatedClientsContractsRouteWithChildren
  '/_authenticated/departments/$deptId': typeof AuthenticatedDepartmentsDeptIdRoute
  '/_authenticated/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/_authenticated/finance/debtors': typeof AuthenticatedFinanceDebtorsRoute
  '/_authenticated/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/_authenticated/finance/payroll-compliance': typeof AuthenticatedFinancePayrollComplianceRoute
  '/_authenticated/finance/reports': typeof AuthenticatedFinanceReportsRouteWithChildren
  '/_authenticated/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/_authenticated/finance/upload': typeof AuthenticatedFinanceUploadRoute
  '/_authenticated/hr/projects': typeof AuthenticatedHrProjectsRoute
  '/_authenticated/hr/recruitment': typeof AuthenticatedHrRecruitmentRoute
  '/_authenticated/it/hrms-clients': typeof AuthenticatedItHrmsClientsRoute
  '/_authenticated/it/systems-sites': typeof AuthenticatedItSystemsSitesRoute
  '/_authenticated/it/tickets': typeof AuthenticatedItTicketsRoute
  '/_authenticated/marketing/blog': typeof AuthenticatedMarketingBlogRouteWithChildren
  '/_authenticated/marketing/campaigns': typeof AuthenticatedMarketingCampaignsRoute
  '/_authenticated/marketing/leads': typeof AuthenticatedMarketingLeadsRoute
  '/_authenticated/marketing/website-analytics': typeof AuthenticatedMarketingWebsiteAnalyticsRoute
  '/_authenticated/pipeline/engagements': typeof AuthenticatedPipelineEngagementsRoute
  '/_authenticated/pipeline/projects': typeof AuthenticatedPipelineProjectsRoute
  '/_authenticated/pipeline/tenders': typeof AuthenticatedPipelineTendersRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/department': typeof AuthenticatedProjectsDepartmentRoute
  '/_authenticated/projects/mine': typeof AuthenticatedProjectsMineRoute
  '/_authenticated/reports/departments': typeof AuthenticatedReportsDepartmentsRouteWithChildren
  '/_authenticated/reports/projects': typeof AuthenticatedReportsProjectsRoute
  '/_authenticated/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/_authenticated/tender/$tenderId': typeof AuthenticatedTenderTenderIdRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/departments/': typeof AuthenticatedDepartmentsIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/hr/': typeof AuthenticatedHrIndexRoute
  '/_authenticated/it/': typeof AuthenticatedItIndexRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/pipeline/': typeof AuthenticatedPipelineIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/tender/': typeof AuthenticatedTenderIndexRoute
  '/_authenticated/clients/contracts/$id': typeof AuthenticatedClientsContractsIdRoute
  '/_authenticated/engagements/$anchorType/$anchorId': typeof AuthenticatedEngagementsAnchorTypeAnchorIdRoute
  '/_authenticated/finance/reports/$id': typeof AuthenticatedFinanceReportsIdRoute
  '/_authenticated/marketing/blog/$postId': typeof AuthenticatedMarketingBlogPostIdRoute
  '/_authenticated/reports/departments/finance': typeof AuthenticatedReportsDepartmentsFinanceRoute
  '/_authenticated/reports/departments/hr': typeof AuthenticatedReportsDepartmentsHrRoute
  '/_authenticated/reports/departments/it': typeof AuthenticatedReportsDepartmentsItRoute
  '/_authenticated/reports/departments/marketing': typeof AuthenticatedReportsDepartmentsMarketingRoute
  '/_authenticated/reports/departments/tender': typeof AuthenticatedReportsDepartmentsTenderRoute
  '/_authenticated/clients/contracts/': typeof AuthenticatedClientsContractsIndexRoute
  '/_authenticated/finance/reports/': typeof AuthenticatedFinanceReportsIndexRoute
  '/_authenticated/marketing/blog/': typeof AuthenticatedMarketingBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/set-password'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/finance'
    | '/guide'
    | '/hr'
    | '/it'
    | '/marketing'
    | '/operations'
    | '/pipeline'
    | '/projects'
    | '/reports'
    | '/requests'
    | '/tender'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/users'
    | '/clients/contracts'
    | '/departments/$deptId'
    | '/finance/budgets'
    | '/finance/debtors'
    | '/finance/invoices'
    | '/finance/payroll-compliance'
    | '/finance/reports'
    | '/finance/revenue'
    | '/finance/upload'
    | '/hr/projects'
    | '/hr/recruitment'
    | '/it/hrms-clients'
    | '/it/systems-sites'
    | '/it/tickets'
    | '/marketing/blog'
    | '/marketing/campaigns'
    | '/marketing/leads'
    | '/marketing/website-analytics'
    | '/pipeline/engagements'
    | '/pipeline/projects'
    | '/pipeline/tenders'
    | '/projects/$projectId'
    | '/projects/department'
    | '/projects/mine'
    | '/reports/departments'
    | '/reports/projects'
    | '/requests/$requestId'
    | '/tender/$tenderId'
    | '/clients/'
    | '/departments/'
    | '/finance/'
    | '/hr/'
    | '/it/'
    | '/marketing/'
    | '/pipeline/'
    | '/projects/'
    | '/reports/'
    | '/requests/'
    | '/tender/'
    | '/clients/contracts/$id'
    | '/engagements/$anchorType/$anchorId'
    | '/finance/reports/$id'
    | '/marketing/blog/$postId'
    | '/reports/departments/finance'
    | '/reports/departments/hr'
    | '/reports/departments/it'
    | '/reports/departments/marketing'
    | '/reports/departments/tender'
    | '/clients/contracts/'
    | '/finance/reports/'
    | '/marketing/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/set-password'
    | '/calendar'
    | '/dashboard'
    | '/documents'
    | '/guide'
    | '/operations'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/users'
    | '/departments/$deptId'
    | '/finance/budgets'
    | '/finance/debtors'
    | '/finance/invoices'
    | '/finance/payroll-compliance'
    | '/finance/revenue'
    | '/finance/upload'
    | '/hr/projects'
    | '/hr/recruitment'
    | '/it/hrms-clients'
    | '/it/systems-sites'
    | '/it/tickets'
    | '/marketing/campaigns'
    | '/marketing/leads'
    | '/marketing/website-analytics'
    | '/pipeline/engagements'
    | '/pipeline/projects'
    | '/pipeline/tenders'
    | '/projects/$projectId'
    | '/projects/department'
    | '/projects/mine'
    | '/reports/departments'
    | '/reports/projects'
    | '/requests/$requestId'
    | '/tender/$tenderId'
    | '/clients'
    | '/departments'
    | '/finance'
    | '/hr'
    | '/it'
    | '/marketing'
    | '/pipeline'
    | '/projects'
    | '/reports'
    | '/requests'
    | '/tender'
    | '/clients/contracts/$id'
    | '/engagements/$anchorType/$anchorId'
    | '/finance/reports/$id'
    | '/marketing/blog/$postId'
    | '/reports/departments/finance'
    | '/reports/departments/hr'
    | '/reports/departments/it'
    | '/reports/departments/marketing'
    | '/reports/departments/tender'
    | '/clients/contracts'
    | '/finance/reports'
    | '/marketing/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/set-password'
    | '/_authenticated/calendar'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/documents'
    | '/_authenticated/finance'
    | '/_authenticated/guide'
    | '/_authenticated/hr'
    | '/_authenticated/it'
    | '/_authenticated/marketing'
    | '/_authenticated/operations'
    | '/_authenticated/pipeline'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/requests'
    | '/_authenticated/tender'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/users'
    | '/_authenticated/clients/contracts'
    | '/_authenticated/departments/$deptId'
    | '/_authenticated/finance/budgets'
    | '/_authenticated/finance/debtors'
    | '/_authenticated/finance/invoices'
    | '/_authenticated/finance/payroll-compliance'
    | '/_authenticated/finance/reports'
    | '/_authenticated/finance/revenue'
    | '/_authenticated/finance/upload'
    | '/_authenticated/hr/projects'
    | '/_authenticated/hr/recruitment'
    | '/_authenticated/it/hrms-clients'
    | '/_authenticated/it/systems-sites'
    | '/_authenticated/it/tickets'
    | '/_authenticated/marketing/blog'
    | '/_authenticated/marketing/campaigns'
    | '/_authenticated/marketing/leads'
    | '/_authenticated/marketing/website-analytics'
    | '/_authenticated/pipeline/engagements'
    | '/_authenticated/pipeline/projects'
    | '/_authenticated/pipeline/tenders'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/department'
    | '/_authenticated/projects/mine'
    | '/_authenticated/reports/departments'
    | '/_authenticated/reports/projects'
    | '/_authenticated/requests/$requestId'
    | '/_authenticated/tender/$tenderId'
    | '/_authenticated/clients/'
    | '/_authenticated/departments/'
    | '/_authenticated/finance/'
    | '/_authenticated/hr/'
    | '/_authenticated/it/'
    | '/_authenticated/marketing/'
    | '/_authenticated/pipeline/'
    | '/_authenticated/projects/'
    | '/_authenticated/reports/'
    | '/_authenticated/requests/'
    | '/_authenticated/tender/'
    | '/_authenticated/clients/contracts/$id'
    | '/_authenticated/engagements/$anchorType/$anchorId'
    | '/_authenticated/finance/reports/$id'
    | '/_authenticated/marketing/blog/$postId'
    | '/_authenticated/reports/departments/finance'
    | '/_authenticated/reports/departments/hr'
    | '/_authenticated/reports/departments/it'
    | '/_authenticated/reports/departments/marketing'
    | '/_authenticated/reports/departments/tender'
    | '/_authenticated/clients/contracts/'
    | '/_authenticated/finance/reports/'
    | '/_authenticated/marketing/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tender': {
      id: '/_authenticated/tender'
      path: '/tender'
      fullPath: '/tender'
      preLoaderRoute: typeof AuthenticatedTenderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/it': {
      id: '/_authenticated/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof AuthenticatedItRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tender/': {
      id: '/_authenticated/tender/'
      path: '/'
      fullPath: '/tender/'
      preLoaderRoute: typeof AuthenticatedTenderIndexRouteImport
      parentRoute: typeof AuthenticatedTenderRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/pipeline/': {
      id: '/_authenticated/pipeline/'
      path: '/'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof AuthenticatedPipelineIndexRouteImport
      parentRoute: typeof AuthenticatedPipelineRoute
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/it/': {
      id: '/_authenticated/it/'
      path: '/'
      fullPath: '/it/'
      preLoaderRoute: typeof AuthenticatedItIndexRouteImport
      parentRoute: typeof AuthenticatedItRoute
    }
    '/_authenticated/hr/': {
      id: '/_authenticated/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof AuthenticatedHrIndexRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/departments/': {
      id: '/_authenticated/departments/'
      path: '/'
      fullPath: '/departments/'
      preLoaderRoute: typeof AuthenticatedDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedDepartmentsRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/tender/$tenderId': {
      id: '/_authenticated/tender/$tenderId'
      path: '/$tenderId'
      fullPath: '/tender/$tenderId'
      preLoaderRoute: typeof AuthenticatedTenderTenderIdRouteImport
      parentRoute: typeof AuthenticatedTenderRoute
    }
    '/_authenticated/requests/$requestId': {
      id: '/_authenticated/requests/$requestId'
      path: '/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_authenticated/reports/projects': {
      id: '/_authenticated/reports/projects'
      path: '/projects'
      fullPath: '/reports/projects'
      preLoaderRoute: typeof AuthenticatedReportsProjectsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/departments': {
      id: '/_authenticated/reports/departments'
      path: '/departments'
      fullPath: '/reports/departments'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/projects/mine': {
      id: '/_authenticated/projects/mine'
      path: '/mine'
      fullPath: '/projects/mine'
      preLoaderRoute: typeof AuthenticatedProjectsMineRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/department': {
      id: '/_authenticated/projects/department'
      path: '/department'
      fullPath: '/projects/department'
      preLoaderRoute: typeof AuthenticatedProjectsDepartmentRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/pipeline/tenders': {
      id: '/_authenticated/pipeline/tenders'
      path: '/tenders'
      fullPath: '/pipeline/tenders'
      preLoaderRoute: typeof AuthenticatedPipelineTendersRouteImport
      parentRoute: typeof AuthenticatedPipelineRoute
    }
    '/_authenticated/pipeline/projects': {
      id: '/_authenticated/pipeline/projects'
      path: '/projects'
      fullPath: '/pipeline/projects'
      preLoaderRoute: typeof AuthenticatedPipelineProjectsRouteImport
      parentRoute: typeof AuthenticatedPipelineRoute
    }
    '/_authenticated/pipeline/engagements': {
      id: '/_authenticated/pipeline/engagements'
      path: '/engagements'
      fullPath: '/pipeline/engagements'
      preLoaderRoute: typeof AuthenticatedPipelineEngagementsRouteImport
      parentRoute: typeof AuthenticatedPipelineRoute
    }
    '/_authenticated/marketing/website-analytics': {
      id: '/_authenticated/marketing/website-analytics'
      path: '/website-analytics'
      fullPath: '/marketing/website-analytics'
      preLoaderRoute: typeof AuthenticatedMarketingWebsiteAnalyticsRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/leads': {
      id: '/_authenticated/marketing/leads'
      path: '/leads'
      fullPath: '/marketing/leads'
      preLoaderRoute: typeof AuthenticatedMarketingLeadsRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/campaigns': {
      id: '/_authenticated/marketing/campaigns'
      path: '/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof AuthenticatedMarketingCampaignsRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/blog': {
      id: '/_authenticated/marketing/blog'
      path: '/blog'
      fullPath: '/marketing/blog'
      preLoaderRoute: typeof AuthenticatedMarketingBlogRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/it/tickets': {
      id: '/_authenticated/it/tickets'
      path: '/tickets'
      fullPath: '/it/tickets'
      preLoaderRoute: typeof AuthenticatedItTicketsRouteImport
      parentRoute: typeof AuthenticatedItRoute
    }
    '/_authenticated/it/systems-sites': {
      id: '/_authenticated/it/systems-sites'
      path: '/systems-sites'
      fullPath: '/it/systems-sites'
      preLoaderRoute: typeof AuthenticatedItSystemsSitesRouteImport
      parentRoute: typeof AuthenticatedItRoute
    }
    '/_authenticated/it/hrms-clients': {
      id: '/_authenticated/it/hrms-clients'
      path: '/hrms-clients'
      fullPath: '/it/hrms-clients'
      preLoaderRoute: typeof AuthenticatedItHrmsClientsRouteImport
      parentRoute: typeof AuthenticatedItRoute
    }
    '/_authenticated/hr/recruitment': {
      id: '/_authenticated/hr/recruitment'
      path: '/recruitment'
      fullPath: '/hr/recruitment'
      preLoaderRoute: typeof AuthenticatedHrRecruitmentRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/projects': {
      id: '/_authenticated/hr/projects'
      path: '/projects'
      fullPath: '/hr/projects'
      preLoaderRoute: typeof AuthenticatedHrProjectsRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/finance/upload': {
      id: '/_authenticated/finance/upload'
      path: '/upload'
      fullPath: '/finance/upload'
      preLoaderRoute: typeof AuthenticatedFinanceUploadRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/revenue': {
      id: '/_authenticated/finance/revenue'
      path: '/revenue'
      fullPath: '/finance/revenue'
      preLoaderRoute: typeof AuthenticatedFinanceRevenueRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/reports': {
      id: '/_authenticated/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof AuthenticatedFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/payroll-compliance': {
      id: '/_authenticated/finance/payroll-compliance'
      path: '/payroll-compliance'
      fullPath: '/finance/payroll-compliance'
      preLoaderRoute: typeof AuthenticatedFinancePayrollComplianceRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/invoices': {
      id: '/_authenticated/finance/invoices'
      path: '/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AuthenticatedFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/debtors': {
      id: '/_authenticated/finance/debtors'
      path: '/debtors'
      fullPath: '/finance/debtors'
      preLoaderRoute: typeof AuthenticatedFinanceDebtorsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/budgets': {
      id: '/_authenticated/finance/budgets'
      path: '/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof AuthenticatedFinanceBudgetsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/departments/$deptId': {
      id: '/_authenticated/departments/$deptId'
      path: '/$deptId'
      fullPath: '/departments/$deptId'
      preLoaderRoute: typeof AuthenticatedDepartmentsDeptIdRouteImport
      parentRoute: typeof AuthenticatedDepartmentsRoute
    }
    '/_authenticated/clients/contracts': {
      id: '/_authenticated/clients/contracts'
      path: '/contracts'
      fullPath: '/clients/contracts'
      preLoaderRoute: typeof AuthenticatedClientsContractsRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/blog/': {
      id: '/_authenticated/marketing/blog/'
      path: '/'
      fullPath: '/marketing/blog/'
      preLoaderRoute: typeof AuthenticatedMarketingBlogIndexRouteImport
      parentRoute: typeof AuthenticatedMarketingBlogRoute
    }
    '/_authenticated/finance/reports/': {
      id: '/_authenticated/finance/reports/'
      path: '/'
      fullPath: '/finance/reports/'
      preLoaderRoute: typeof AuthenticatedFinanceReportsIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceReportsRoute
    }
    '/_authenticated/clients/contracts/': {
      id: '/_authenticated/clients/contracts/'
      path: '/'
      fullPath: '/clients/contracts/'
      preLoaderRoute: typeof AuthenticatedClientsContractsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsContractsRoute
    }
    '/_authenticated/reports/departments/tender': {
      id: '/_authenticated/reports/departments/tender'
      path: '/tender'
      fullPath: '/reports/departments/tender'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsTenderRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/reports/departments/marketing': {
      id: '/_authenticated/reports/departments/marketing'
      path: '/marketing'
      fullPath: '/reports/departments/marketing'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsMarketingRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/reports/departments/it': {
      id: '/_authenticated/reports/departments/it'
      path: '/it'
      fullPath: '/reports/departments/it'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsItRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/reports/departments/hr': {
      id: '/_authenticated/reports/departments/hr'
      path: '/hr'
      fullPath: '/reports/departments/hr'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsHrRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/reports/departments/finance': {
      id: '/_authenticated/reports/departments/finance'
      path: '/finance'
      fullPath: '/reports/departments/finance'
      preLoaderRoute: typeof AuthenticatedReportsDepartmentsFinanceRouteImport
      parentRoute: typeof AuthenticatedReportsDepartmentsRoute
    }
    '/_authenticated/marketing/blog/$postId': {
      id: '/_authenticated/marketing/blog/$postId'
      path: '/$postId'
      fullPath: '/marketing/blog/$postId'
      preLoaderRoute: typeof AuthenticatedMarketingBlogPostIdRouteImport
      parentRoute: typeof AuthenticatedMarketingBlogRoute
    }
    '/_authenticated/finance/reports/$id': {
      id: '/_authenticated/finance/reports/$id'
      path: '/$id'
      fullPath: '/finance/reports/$id'
      preLoaderRoute: typeof AuthenticatedFinanceReportsIdRouteImport
      parentRoute: typeof AuthenticatedFinanceReportsRoute
    }
    '/_authenticated/engagements/$anchorType/$anchorId': {
      id: '/_authenticated/engagements/$anchorType/$anchorId'
      path: '/engagements/$anchorType/$anchorId'
      fullPath: '/engagements/$anchorType/$anchorId'
      preLoaderRoute: typeof AuthenticatedEngagementsAnchorTypeAnchorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/contracts/$id': {
      id: '/_authenticated/clients/contracts/$id'
      path: '/$id'
      fullPath: '/clients/contracts/$id'
      preLoaderRoute: typeof AuthenticatedClientsContractsIdRouteImport
      parentRoute: typeof AuthenticatedClientsContractsRoute
    }
  }
}

interface AuthenticatedClientsContractsRouteChildren {
  AuthenticatedClientsContractsIdRoute: typeof AuthenticatedClientsContractsIdRoute
  AuthenticatedClientsContractsIndexRoute: typeof AuthenticatedClientsContractsIndexRoute
}

const AuthenticatedClientsContractsRouteChildren: AuthenticatedClientsContractsRouteChildren =
  {
    AuthenticatedClientsContractsIdRoute: AuthenticatedClientsContractsIdRoute,
    AuthenticatedClientsContractsIndexRoute:
      AuthenticatedClientsContractsIndexRoute,
  }

const AuthenticatedClientsContractsRouteWithChildren =
  AuthenticatedClientsContractsRoute._addFileChildren(
    AuthenticatedClientsContractsRouteChildren,
  )

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsContractsRoute: typeof AuthenticatedClientsContractsRouteWithChildren
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsContractsRoute:
    AuthenticatedClientsContractsRouteWithChildren,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedDepartmentsRouteChildren {
  AuthenticatedDepartmentsDeptIdRoute: typeof AuthenticatedDepartmentsDeptIdRoute
  AuthenticatedDepartmentsIndexRoute: typeof AuthenticatedDepartmentsIndexRoute
}

const AuthenticatedDepartmentsRouteChildren: AuthenticatedDepartmentsRouteChildren =
  {
    AuthenticatedDepartmentsDeptIdRoute: AuthenticatedDepartmentsDeptIdRoute,
    AuthenticatedDepartmentsIndexRoute: AuthenticatedDepartmentsIndexRoute,
  }

const AuthenticatedDepartmentsRouteWithChildren =
  AuthenticatedDepartmentsRoute._addFileChildren(
    AuthenticatedDepartmentsRouteChildren,
  )

interface AuthenticatedFinanceReportsRouteChildren {
  AuthenticatedFinanceReportsIdRoute: typeof AuthenticatedFinanceReportsIdRoute
  AuthenticatedFinanceReportsIndexRoute: typeof AuthenticatedFinanceReportsIndexRoute
}

const AuthenticatedFinanceReportsRouteChildren: AuthenticatedFinanceReportsRouteChildren =
  {
    AuthenticatedFinanceReportsIdRoute: AuthenticatedFinanceReportsIdRoute,
    AuthenticatedFinanceReportsIndexRoute:
      AuthenticatedFinanceReportsIndexRoute,
  }

const AuthenticatedFinanceReportsRouteWithChildren =
  AuthenticatedFinanceReportsRoute._addFileChildren(
    AuthenticatedFinanceReportsRouteChildren,
  )

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceBudgetsRoute: typeof AuthenticatedFinanceBudgetsRoute
  AuthenticatedFinanceDebtorsRoute: typeof AuthenticatedFinanceDebtorsRoute
  AuthenticatedFinanceInvoicesRoute: typeof AuthenticatedFinanceInvoicesRoute
  AuthenticatedFinancePayrollComplianceRoute: typeof AuthenticatedFinancePayrollComplianceRoute
  AuthenticatedFinanceReportsRoute: typeof AuthenticatedFinanceReportsRouteWithChildren
  AuthenticatedFinanceRevenueRoute: typeof AuthenticatedFinanceRevenueRoute
  AuthenticatedFinanceUploadRoute: typeof AuthenticatedFinanceUploadRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceBudgetsRoute: AuthenticatedFinanceBudgetsRoute,
  AuthenticatedFinanceDebtorsRoute: AuthenticatedFinanceDebtorsRoute,
  AuthenticatedFinanceInvoicesRoute: AuthenticatedFinanceInvoicesRoute,
  AuthenticatedFinancePayrollComplianceRoute:
    AuthenticatedFinancePayrollComplianceRoute,
  AuthenticatedFinanceReportsRoute:
    AuthenticatedFinanceReportsRouteWithChildren,
  AuthenticatedFinanceRevenueRoute: AuthenticatedFinanceRevenueRoute,
  AuthenticatedFinanceUploadRoute: AuthenticatedFinanceUploadRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedHrRouteChildren {
  AuthenticatedHrProjectsRoute: typeof AuthenticatedHrProjectsRoute
  AuthenticatedHrRecruitmentRoute: typeof AuthenticatedHrRecruitmentRoute
  AuthenticatedHrIndexRoute: typeof AuthenticatedHrIndexRoute
}

const AuthenticatedHrRouteChildren: AuthenticatedHrRouteChildren = {
  AuthenticatedHrProjectsRoute: AuthenticatedHrProjectsRoute,
  AuthenticatedHrRecruitmentRoute: AuthenticatedHrRecruitmentRoute,
  AuthenticatedHrIndexRoute: AuthenticatedHrIndexRoute,
}

const AuthenticatedHrRouteWithChildren = AuthenticatedHrRoute._addFileChildren(
  AuthenticatedHrRouteChildren,
)

interface AuthenticatedItRouteChildren {
  AuthenticatedItHrmsClientsRoute: typeof AuthenticatedItHrmsClientsRoute
  AuthenticatedItSystemsSitesRoute: typeof AuthenticatedItSystemsSitesRoute
  AuthenticatedItTicketsRoute: typeof AuthenticatedItTicketsRoute
  AuthenticatedItIndexRoute: typeof AuthenticatedItIndexRoute
}

const AuthenticatedItRouteChildren: AuthenticatedItRouteChildren = {
  AuthenticatedItHrmsClientsRoute: AuthenticatedItHrmsClientsRoute,
  AuthenticatedItSystemsSitesRoute: AuthenticatedItSystemsSitesRoute,
  AuthenticatedItTicketsRoute: AuthenticatedItTicketsRoute,
  AuthenticatedItIndexRoute: AuthenticatedItIndexRoute,
}

const AuthenticatedItRouteWithChildren = AuthenticatedItRoute._addFileChildren(
  AuthenticatedItRouteChildren,
)

interface AuthenticatedMarketingBlogRouteChildren {
  AuthenticatedMarketingBlogPostIdRoute: typeof AuthenticatedMarketingBlogPostIdRoute
  AuthenticatedMarketingBlogIndexRoute: typeof AuthenticatedMarketingBlogIndexRoute
}

const AuthenticatedMarketingBlogRouteChildren: AuthenticatedMarketingBlogRouteChildren =
  {
    AuthenticatedMarketingBlogPostIdRoute:
      AuthenticatedMarketingBlogPostIdRoute,
    AuthenticatedMarketingBlogIndexRoute: AuthenticatedMarketingBlogIndexRoute,
  }

const AuthenticatedMarketingBlogRouteWithChildren =
  AuthenticatedMarketingBlogRoute._addFileChildren(
    AuthenticatedMarketingBlogRouteChildren,
  )

interface AuthenticatedMarketingRouteChildren {
  AuthenticatedMarketingBlogRoute: typeof AuthenticatedMarketingBlogRouteWithChildren
  AuthenticatedMarketingCampaignsRoute: typeof AuthenticatedMarketingCampaignsRoute
  AuthenticatedMarketingLeadsRoute: typeof AuthenticatedMarketingLeadsRoute
  AuthenticatedMarketingWebsiteAnalyticsRoute: typeof AuthenticatedMarketingWebsiteAnalyticsRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
}

const AuthenticatedMarketingRouteChildren: AuthenticatedMarketingRouteChildren =
  {
    AuthenticatedMarketingBlogRoute:
      AuthenticatedMarketingBlogRouteWithChildren,
    AuthenticatedMarketingCampaignsRoute: AuthenticatedMarketingCampaignsRoute,
    AuthenticatedMarketingLeadsRoute: AuthenticatedMarketingLeadsRoute,
    AuthenticatedMarketingWebsiteAnalyticsRoute:
      AuthenticatedMarketingWebsiteAnalyticsRoute,
    AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  }

const AuthenticatedMarketingRouteWithChildren =
  AuthenticatedMarketingRoute._addFileChildren(
    AuthenticatedMarketingRouteChildren,
  )

interface AuthenticatedPipelineRouteChildren {
  AuthenticatedPipelineEngagementsRoute: typeof AuthenticatedPipelineEngagementsRoute
  AuthenticatedPipelineProjectsRoute: typeof AuthenticatedPipelineProjectsRoute
  AuthenticatedPipelineTendersRoute: typeof AuthenticatedPipelineTendersRoute
  AuthenticatedPipelineIndexRoute: typeof AuthenticatedPipelineIndexRoute
}

const AuthenticatedPipelineRouteChildren: AuthenticatedPipelineRouteChildren = {
  AuthenticatedPipelineEngagementsRoute: AuthenticatedPipelineEngagementsRoute,
  AuthenticatedPipelineProjectsRoute: AuthenticatedPipelineProjectsRoute,
  AuthenticatedPipelineTendersRoute: AuthenticatedPipelineTendersRoute,
  AuthenticatedPipelineIndexRoute: AuthenticatedPipelineIndexRoute,
}

const AuthenticatedPipelineRouteWithChildren =
  AuthenticatedPipelineRoute._addFileChildren(
    AuthenticatedPipelineRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsDepartmentRoute: typeof AuthenticatedProjectsDepartmentRoute
  AuthenticatedProjectsMineRoute: typeof AuthenticatedProjectsMineRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsDepartmentRoute: AuthenticatedProjectsDepartmentRoute,
  AuthenticatedProjectsMineRoute: AuthenticatedProjectsMineRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedReportsDepartmentsRouteChildren {
  AuthenticatedReportsDepartmentsFinanceRoute: typeof AuthenticatedReportsDepartmentsFinanceRoute
  AuthenticatedReportsDepartmentsHrRoute: typeof AuthenticatedReportsDepartmentsHrRoute
  AuthenticatedReportsDepartmentsItRoute: typeof AuthenticatedReportsDepartmentsItRoute
  AuthenticatedReportsDepartmentsMarketingRoute: typeof AuthenticatedReportsDepartmentsMarketingRoute
  AuthenticatedReportsDepartmentsTenderRoute: typeof AuthenticatedReportsDepartmentsTenderRoute
}

const AuthenticatedReportsDepartmentsRouteChildren: AuthenticatedReportsDepartmentsRouteChildren =
  {
    AuthenticatedReportsDepartmentsFinanceRoute:
      AuthenticatedReportsDepartmentsFinanceRoute,
    AuthenticatedReportsDepartmentsHrRoute:
      AuthenticatedReportsDepartmentsHrRoute,
    AuthenticatedReportsDepartmentsItRoute:
      AuthenticatedReportsDepartmentsItRoute,
    AuthenticatedReportsDepartmentsMarketingRoute:
      AuthenticatedReportsDepartmentsMarketingRoute,
    AuthenticatedReportsDepartmentsTenderRoute:
      AuthenticatedReportsDepartmentsTenderRoute,
  }

const AuthenticatedReportsDepartmentsRouteWithChildren =
  AuthenticatedReportsDepartmentsRoute._addFileChildren(
    AuthenticatedReportsDepartmentsRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsDepartmentsRoute: typeof AuthenticatedReportsDepartmentsRouteWithChildren
  AuthenticatedReportsProjectsRoute: typeof AuthenticatedReportsProjectsRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsDepartmentsRoute:
    AuthenticatedReportsDepartmentsRouteWithChildren,
  AuthenticatedReportsProjectsRoute: AuthenticatedReportsProjectsRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRequestsRouteChildren {
  AuthenticatedRequestsRequestIdRoute: typeof AuthenticatedRequestsRequestIdRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
}

const AuthenticatedRequestsRouteChildren: AuthenticatedRequestsRouteChildren = {
  AuthenticatedRequestsRequestIdRoute: AuthenticatedRequestsRequestIdRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
}

const AuthenticatedRequestsRouteWithChildren =
  AuthenticatedRequestsRoute._addFileChildren(
    AuthenticatedRequestsRouteChildren,
  )

interface AuthenticatedTenderRouteChildren {
  AuthenticatedTenderTenderIdRoute: typeof AuthenticatedTenderTenderIdRoute
  AuthenticatedTenderIndexRoute: typeof AuthenticatedTenderIndexRoute
}

const AuthenticatedTenderRouteChildren: AuthenticatedTenderRouteChildren = {
  AuthenticatedTenderTenderIdRoute: AuthenticatedTenderTenderIdRoute,
  AuthenticatedTenderIndexRoute: AuthenticatedTenderIndexRoute,
}

const AuthenticatedTenderRouteWithChildren =
  AuthenticatedTenderRoute._addFileChildren(AuthenticatedTenderRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRouteWithChildren
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRouteWithChildren
  AuthenticatedItRoute: typeof AuthenticatedItRouteWithChildren
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRouteWithChildren
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRouteWithChildren
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRouteWithChildren
  AuthenticatedTenderRoute: typeof AuthenticatedTenderRouteWithChildren
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedEngagementsAnchorTypeAnchorIdRoute: typeof AuthenticatedEngagementsAnchorTypeAnchorIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRouteWithChildren,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedHrRoute: AuthenticatedHrRouteWithChildren,
  AuthenticatedItRoute: AuthenticatedItRouteWithChildren,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRouteWithChildren,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRouteWithChildren,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRouteWithChildren,
  AuthenticatedTenderRoute: AuthenticatedTenderRouteWithChildren,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedEngagementsAnchorTypeAnchorIdRoute:
    AuthenticatedEngagementsAnchorTypeAnchorIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
